export enum POrderState {
  PAYMENT_WAITING = 'PAYMENT_WAITING',
  PAYMENT_COMPLETE = 'PAYMENT_COMPLETE',
  SHIPPING = 'SHIPPING',
  DELIVERY_COMPLETED = 'DELIVERY_COMPLETED',
  ORDER_CANCEL = 'ORDER_CANCEL',
}
